# Generated by Django 2.2 on 2019-05-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ess_gender', models.CharField(max_length=1)),
                ('ess_age', models.CharField(max_length=1)),
                ('ess_marital', models.CharField(max_length=1)),
                ('ess_job', models.CharField(max_length=1)),
                ('province', models.CharField(max_length=1)),
                ('city', models.CharField(max_length=1)),
                ('prefer', models.CharField(max_length=1)),
                ('frequency', models.CharField(max_length=1)),
                ('wineFrequency', models.CharField(max_length=1)),
                ('side', models.CharField(max_length=1)),
                ('area_grade', models.CharField(max_length=1)),
                ('choice2', models.CharField(max_length=1)),
            ],
        ),
    ]
